# **Exploratory Data Analysis of Historical Stock Market Data**

## **Introduction**:

This project focuses on the Exploratory Data Analysis (EDA) of historical stock market data from 1970 to 2018. We will use two datasets. The historical_stocks.csv dataset contains information about stocks, including ticker, exchange, company name, sector, and industry. The historical_stock_prices.csv dataset contains historical trading data, including ticker, open, close, adjusted close, low, high, volume, and date. The two datasets are linked through the ticker column.
Using Python, we will explore and understand the datasets before conducting more advanced analyses. Specifically, we will inspect the data, assess data quality, explore stock information, identify unusual observations, create visualizations, analyze stock prices over time, and identify opportunities for further analysis.

## **Part 1 — Load and Understand the Data**

### **Import libraries**

In [1]:
# Import libraries

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### **Load the datasets**

In [4]:
# Load the datasets

stock_data = pd.read_csv("historical_stocks.csv")
stock_price_data = pd.read_csv("historical_stock_prices.csv")

### **Inspect to understand the Datasets**

In [ ]:
# Display the first five rows for the stock data

stock_data.head()

,ticker,exchange,name,sector,industry
0,PIH,NASDAQ,"1347 PROPERTY INSURANCE HOLDINGS, INC.",FINANCE,PROPERTY-CASUALTY INSURERS
1,PIHPP,NASDAQ,"1347 PROPERTY INSURANCE HOLDINGS, INC.",FINANCE,PROPERTY-CASUALTY INSURERS
2,TURN,NASDAQ,180 DEGREE CAPITAL CORP.,FINANCE,FINANCE/INVESTORS SERVICES
3,FLWS,NASDAQ,"1-800 FLOWERS.COM, INC.",CONSUMER SERVICES,OTHER SPECIALTY STORES
4,FCCY,NASDAQ,1ST CONSTITUTION BANCORP (NJ),FINANCE,SAVINGS INSTITUTIONS

In [6]:
# Display the first five rows for the stock price data

stock_price_data.head()

  ticker   open  close  adj_close    low   high   volume        date
0    AHH  11.50  11.58   8.493155  11.25  11.68  4633900  2013-05-08
1    AHH  11.66  11.55   8.471151  11.50  11.66   275800  2013-05-09
2    AHH  11.55  11.60   8.507822  11.50  11.60   277100  2013-05-10
3    AHH  11.63  11.65   8.544494  11.55  11.65   147400  2013-05-13
4    AHH  11.60  11.53   8.456484  11.50  11.60   184100  2013-05-14

In [11]:
# Find the company info for AHH

stock_data[stock_data["ticker"] == "AHH"]

     ticker exchange                             name   sector     industry
3543    AHH     NYSE  ARMADA HOFFLER PROPERTIES, INC.  FINANCE  REAL ESTATE

In [7]:
# Inspect the datasets structure and dimension

stock_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 6460 entries, 0 to 6459
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ticker    6460 non-null   str
 1   exchange  6460 non-null   str
 2   name      6460 non-null   str
 3   sector    5020 non-null   str
 4   industry  5020 non-null   str
dtypes: str(5)
memory usage: 640.9 KB

In [8]:
stock_price_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 20973889 entries, 0 to 20973888
Data columns (total 8 columns):
 #   Column     Dtype
---  ------     -----
 0   ticker     str
 1   open       float64
 2   close      float64
 3   adj_close  float64
 4   low        float64
 5   high       float64
 6   volume     int64
 7   date       str
dtypes: float64(5), int64(1), str(2)
memory usage: 1.5 GB

In [9]:
stock_price_data.shape

(20973889, 8)

In [10]:
stock_data.shape

(6460, 5)